python test_with_candidates.py \
    --model lavt \
    --swin_type base \
    --dataset Gref \
    --split val  \
    --resume ./checkpoints/gref_corrections.pth \
    --workers 4 \
    --ddp_trained_weights \
    --window12 \
    --img_size 480 \
    --ck_bert ./bert/models \
    --device cuda:3