python test_with_candidates.py \
    --model lavt \
    --swin_type base \
    --dataset unc \
    --split val  \
    --resume checkpoints/model_best_refcoco.pth \
    --configs ./configs/val/config.json \
    --workers 4 \
    --ddp_trained_weights \
    --window12 \
    --img_size 480 \
    --ck_bert ./bert/models \
    --device cuda:0 \