python test.py \
    --model lavt \
    --swin_type base \
    --dataset refcoco \
    --split val  \
    --resume output/refcoco_20250821_234057/checkpoints/refcoco_pseudo_consistent.pth \
    --workers 8 \
    --ddp_trained_weights \
    --window12 \
    --img_size 480 \
    --ck_bert ./bert/models \
    --device cuda:5